# Numpy Library

In [20]:
import numpy as np

In [21]:
np1 = np.array([1,2,3,4]) #array([1, 2, 3, 4])
print(np1.shape) # (4,)
print(type(np1)) # <class 'numpy.ndarray'>
np1

(4,)
<class 'numpy.ndarray'>


array([1, 2, 3, 4])

# Array creation Routines
[array-creation](https://numpy.org/devdocs/reference/routines.array-creation.html)

# 1. Array function

In [22]:
Mat1 = np.array( [[1,2], [3,4]] )
print("Mat1.shape={}".format(Mat1.shape))
print("Mat1.dtype={}".format(Mat1.dtype))


Mat1.shape=(2, 2)
Mat1.dtype=int64


# 2. ARANGE function
Return evenly spaced values within a given interval.

In [23]:
Mat2 = np.arange(0, 10, 1)
Mat2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 3. Linspace function
Returns evenly spaced numbers 

In [15]:
Mat3 = np.linspace(0, 5, 5) #Returns evenly spaced numbers inclusive
Mat3

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

# 4. Random.rand function
Create an array of the given shape and populate it with random samples from a uniform distribution over [0,1)

In [13]:
Mat1 = np.random.rand(0) # Empty Array
Mat2 = np.random.rand(1) # Vector
Mat3 = np.random.rand(1,2) # 1 x 2 array
Mat4 = np.random.rand(2,2) # 2 x 2 array
Mat5 = np.random.rand(1,1,1) # 1 x 1 x 1 array

print("{} {}, shape={}".format("rand(0) =", Mat1, Mat1.shape))
print("{} {}, shape={}".format("rand(1) =", Mat2, Mat2.shape))
print("{} {}, shape={}".format("rand(1,2) =", Mat3, Mat3.shape))
print("{} {}, shape={}".format("rand(2,2) =", Mat4, Mat4.shape))
print("{} {}, shape={}".format("rand(1,1,1) =", Mat5, Mat5.shape))

rand(0) = [], shape=(0,)
rand(1) = [0.84859169], shape=(1,)
rand(1,2) = [[0.12394497 0.29039837]], shape=(1, 2)
rand(2,2) = [[0.5108869  0.46195282]
 [0.99206887 0.67980549]], shape=(2, 2)
rand(1,1,1) = [[[0.04300632]]], shape=(1, 1, 1)


In [ ]:
# 5. Random.randN function

# 5. Diag function
Creates an array filling in the elements diagonally

In [14]:
print(np.diag([3,7,9,15,25]))

[[ 3  0  0  0  0]
 [ 0  7  0  0  0]
 [ 0  0  9  0  0]
 [ 0  0  0 15  0]
 [ 0  0  0  0 25]]
